version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: homeos
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  web:
    build: .
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/homeos
      JWT_SECRET: changeme
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - .:/app
volumes:
  db-data:
